version: "3.2"
services:

  userdbtest:
    container_name: 'userdbtest'
    image: mysql:8.0
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdb
    ports:
      - 50:3306
    networks:
      - teusnetwork

networks:
  teusnetwork:
    external:
      name: teusnetwork
